spring.application.name=transparencia-backend
server.port=${SERVER_PORT:8080}

# Configuracion de la Base de Datos parametrizada
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/saip_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&serverTimezone=America/Lima}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=${DB_DRIVER:com.mysql.cj.jdbc.Driver}

# Hibernate y JPA
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=${JPA_DIALECT:org.hibernate.dialect.MySQLDialect}

# Documentacion OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Seguridad JWT y Archivos
jwt.secret=${JWT_SECRET:UnaClaveSuperSecretaQueTengaAlMenos32CaracteresParaHMACSHA256}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
app.upload-dir=${APP_UPLOAD_DIR:uploads}