/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/solicitudes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["obtenerPorId"];
        put: operations["actualizar"];
        post?: never;
        delete: operations["eliminar"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ttaip/calificacion/{apelacionId}/subsanar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["requerirSubsanacion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ttaip/calificacion/{apelacionId}/no-presentado": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["declararNoPresentado"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ttaip/calificacion/{apelacionId}/inadmitir": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["inadmitirApelacion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ttaip/calificacion/{apelacionId}/admitir": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["admitirApelacion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/solicitudes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listar"];
        put?: never;
        post: operations["crear"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/respuestas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listar_1"];
        put?: never;
        post: operations["crear_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/respuestas/denegar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["denegarSolicitud"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/respuestas/aceptar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["aceptarSolicitud"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/registro": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registrar ciudadano
         * @description Registra un ciudadano con email, password y DNI
         */
        post: operations["registro"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Iniciar sesion
         * @description Autentica al usuario y retorna JWT con datos de perfil
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/solicitudes/{id}/estado": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["cambiarEstado"];
        trace?: never;
    };
    "/api/ttaip/subsanacion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listarSubsanacion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ttaip/segunda-calificacion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listarSegundaCalificacion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ttaip/resueltas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listarResueltas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ttaip/pendientes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listarPendientes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ttaip/estadisticas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["obtenerEstadisticas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ttaip/en-resolucion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listarEnResolucion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ttaip/en-calificacion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listarEnCalificacion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/solicitudes/expediente/{expediente}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["obtenerPorExpediente"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/solicitudes/estado/{estado}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listarPorEstado"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/solicitudes/estadisticas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["obtenerEstadisticas_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/solicitudes/entidad/{entidadId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listarPorEntidad"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/solicitudes/entidad/{entidadId}/estadisticas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["obtenerEstadisticasPorEntidad"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/solicitudes/ciudadano/{ciudadanoId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listarPorCiudadano"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/solicitudes/ciudadano/{ciudadanoId}/estadisticas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["obtenerEstadisticasPorCiudadano"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/respuestas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["obtenerPorId_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/respuestas/solicitud/{solicitudId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["obtenerPorSolicitud"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/respuestas/causales-denegacion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["obtenerCausalesDenegacion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verificar-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verificar disponibilidad de email */
        get: operations["verificarEmail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verificar-dni": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verificar disponibilidad de DNI */
        get: operations["verificarDni"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me/{usuarioId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener usuario
         * @description Retorna datos basicos del usuario por usuarioId
         */
        get: operations["obtenerUsuarioActual"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ActualizarSolicitudRequest: {
            asunto?: string;
            descripcion?: string;
            tipoInformacion?: string;
            prioridad?: string;
            formatoDigital?: boolean;
            formatoFisico?: boolean;
            copiaSimple?: boolean;
            copiaCertificada?: boolean;
        };
        /** @description Documento adjunto a solicitud, respuesta, apelacion o resolucion */
        DocumentoDTO: {
            /** Format: int64 */
            id?: number;
            nombreArchivo?: string;
            rutaArchivo?: string;
            tipoArchivo?: string;
            /** Format: int64 */
            tamanio?: number;
            tipoDocumento?: string;
            fechaSubida?: string;
        };
        /** @description Respuesta de funcionario a solicitud SAIP */
        RespuestaDTO: {
            /** Format: int64 */
            id?: number;
            /**
             * @description Tipo de respuesta
             * @example ENTREGA_TOTAL
             * @enum {string}
             */
            tipoRespuesta?: "ENTREGA_TOTAL" | "ENTREGA_PARCIAL" | "DENEGACION_TOTAL" | "SILENCIO_ADMINISTRATIVO";
            decision?: string;
            contenido?: string;
            causalDenegatoria?: string;
            fundamentoLegal?: string;
            fechaRespuesta?: string;
            /** Format: int64 */
            funcionarioId?: number;
            funcionarioNombre?: string;
            documentos?: components["schemas"]["DocumentoDTO"][];
        };
        /** @description Solicitud de Acceso a la Informacion Publica (SAIP) */
        SolicitudDTO: {
            /** Format: int64 */
            id?: number;
            /**
             * @description Numero de solicitud
             * @example SAIP-2025-00512
             */
            expediente?: string;
            /** @description Asunto de la solicitud */
            asunto?: string;
            descripcion?: string;
            /**
             * @description Estado actual
             * @example RECEPCIONADA
             * @enum {string}
             */
            estado?: "RECEPCIONADA" | "EN_REVISION" | "PENDIENTE_INFORMACION" | "RESPONDIDA" | "DENEGADA" | "CONCLUIDA" | "VENCIDA";
            /**
             * @description Nivel de prioridad
             * @example MEDIA
             * @enum {string}
             */
            prioridad?: "BAJA" | "NORMAL" | "MEDIA" | "ALTA" | "URGENTE";
            /**
             * @description Semaforo de plazo
             * @example VERDE
             * @enum {string}
             */
            semaforo?: "VERDE" | "AMBAR" | "ROJO" | "NEGRO";
            fechaPresentacion?: string;
            /** @description Fecha limite (10 dias habiles) */
            fechaLimite?: string;
            /**
             * Format: int32
             * @description Dias habiles restantes
             */
            diasRestantes?: number;
            /** Format: int64 */
            ciudadanoId?: number;
            ciudadanoNombre?: string;
            ciudadanoDni?: string;
            /** Format: int64 */
            entidadId?: number;
            entidadNombre?: string;
            entidadAcronimo?: string;
            formatoDigital?: boolean;
            formatoFisico?: boolean;
            copiaSimple?: boolean;
            copiaCertificada?: boolean;
            tipoInformacion?: string;
            respuesta?: components["schemas"]["RespuestaDTO"];
            documentos?: components["schemas"]["DocumentoDTO"][];
        };
        CalificacionRequest: {
            fundamentos?: string;
            /** Format: int64 */
            miembroId?: number;
            observaciones?: string;
            /** Format: int32 */
            diasSubsanacion?: number;
        };
        ApelacionDTO: {
            /** Format: int64 */
            idApelacion?: number;
            expediente?: string;
            estado?: string;
            resultado?: string;
            /** Format: date-time */
            fechaApelacion?: string;
            /** Format: date-time */
            fechaSubsanacion?: string;
            /** Format: int32 */
            diasSubsanacion?: number;
            /** Format: int64 */
            ciudadanoId?: number;
            ciudadanoNombre?: string;
            /** Format: int64 */
            solicitudId?: number;
            solicitudExpediente?: string;
        };
        CrearSolicitudRequest: {
            asunto?: string;
            descripcion?: string;
            /** Format: int64 */
            ciudadanoId: number;
            /** Format: int64 */
            entidadId: number;
            formatoDigital?: boolean;
            formatoFisico?: boolean;
            copiaSimple?: boolean;
            copiaCertificada?: boolean;
            tipoInformacion?: string;
        };
        CrearRespuestaRequest: {
            /** Format: int64 */
            solicitudId: number;
            /** Format: int64 */
            funcionarioId: number;
            tipoRespuesta?: string;
            contenido?: string;
            causalDenegatoria?: string;
            fundamentoLegal?: string;
            formatoEntrega?: string;
            /** Format: int32 */
            plazoEntrega?: number;
        };
        RegistroRequestDTO: {
            email?: string;
            password?: string;
            dni?: string;
            nombreCompleto?: string;
            telefono?: string;
            direccion?: string;
        };
        LoginRequestDTO: {
            identificador?: string;
            password?: string;
        };
        ActualizarEstadoSolicitudRequest: {
            estado?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    obtenerPorId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SolicitudDTO"];
                };
            };
        };
    };
    actualizar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActualizarSolicitudRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SolicitudDTO"];
                };
            };
        };
    };
    eliminar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    requerirSubsanacion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                apelacionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalificacionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApelacionDTO"];
                };
            };
        };
    };
    declararNoPresentado: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                apelacionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalificacionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApelacionDTO"];
                };
            };
        };
    };
    inadmitirApelacion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                apelacionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalificacionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApelacionDTO"];
                };
            };
        };
    };
    admitirApelacion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                apelacionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalificacionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApelacionDTO"];
                };
            };
        };
    };
    listar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SolicitudDTO"][];
                };
            };
        };
    };
    crear: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearSolicitudRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SolicitudDTO"];
                };
            };
        };
    };
    listar_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RespuestaDTO"][];
                };
            };
        };
    };
    crear_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearRespuestaRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RespuestaDTO"];
                };
            };
        };
    };
    denegarSolicitud: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearRespuestaRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RespuestaDTO"];
                };
            };
        };
    };
    aceptarSolicitud: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearRespuestaRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RespuestaDTO"];
                };
            };
        };
    };
    registro: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistroRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: Record<string, never>;
                    };
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: Record<string, never>;
                    };
                };
            };
        };
    };
    cambiarEstado: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActualizarEstadoSolicitudRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SolicitudDTO"];
                };
            };
        };
    };
    listarSubsanacion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApelacionDTO"][];
                };
            };
        };
    };
    listarSegundaCalificacion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApelacionDTO"][];
                };
            };
        };
    };
    listarResueltas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApelacionDTO"][];
                };
            };
        };
    };
    listarPendientes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApelacionDTO"][];
                };
            };
        };
    };
    obtenerEstadisticas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: Record<string, never>;
                    };
                };
            };
        };
    };
    listarEnResolucion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApelacionDTO"][];
                };
            };
        };
    };
    listarEnCalificacion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApelacionDTO"][];
                };
            };
        };
    };
    obtenerPorExpediente: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                expediente: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SolicitudDTO"];
                };
            };
        };
    };
    listarPorEstado: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                estado: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SolicitudDTO"][];
                };
            };
        };
    };
    obtenerEstadisticas_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: Record<string, never>;
                    };
                };
            };
        };
    };
    listarPorEntidad: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entidadId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SolicitudDTO"][];
                };
            };
        };
    };
    obtenerEstadisticasPorEntidad: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entidadId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: Record<string, never>;
                    };
                };
            };
        };
    };
    listarPorCiudadano: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ciudadanoId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SolicitudDTO"][];
                };
            };
        };
    };
    obtenerEstadisticasPorCiudadano: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ciudadanoId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: Record<string, never>;
                    };
                };
            };
        };
    };
    obtenerPorId_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RespuestaDTO"];
                };
            };
        };
    };
    obtenerPorSolicitud: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                solicitudId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RespuestaDTO"];
                };
            };
        };
    };
    obtenerCausalesDenegacion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string[];
                };
            };
        };
    };
    verificarEmail: {
        parameters: {
            query: {
                email: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: Record<string, never>;
                    };
                };
            };
        };
    };
    verificarDni: {
        parameters: {
            query: {
                dni: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: Record<string, never>;
                    };
                };
            };
        };
    };
    obtenerUsuarioActual: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                usuarioId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: Record<string, never>;
                    };
                };
            };
        };
    };
}
