package com.transparencia.api.model.entity;

public enum EstadoApelacion {
    PENDIENTE_ELEVACION, EN_CALIFICACION_1, EN_SUBSANACION, EN_CALIFICACION_2,
    NOTIFICACION_SEGUNDA_CALIFICACION, EN_RESOLUCION, RESUELTO, TENER_POR_NO_PRESENTADO,
    CONCLUSION_SUSTRACCION_MATERIA, CONCLUSION_DESISTIMIENTO, RESUELTO_FUNDADO,
    RESUELTO_FUNDADO_EN_PARTE, RESUELTO_INFUNDADO, RESUELTO_INFUNDADO_EN_PARTE,
    RESUELTO_IMPROCEDENTE
}